  
- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /jenkins/
  - name: delete the previous of kubernetes objects 
    command: kubectl delete -f /jenkins/deployment.yaml
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /jenkins/deployment.yaml
