- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /home/jenkins/
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /home/jenkins/deployment.yaml
