- hosts: test
  tasks:
  - name: copy deployment file to kubernetes master 
    copy:
      src: deployment.yaml
      dest: /root/
  - name: Create a Deployment by reading the definition from a local file
    command: kubectl apply -f /root/deployment.yaml
